apiVersion: v1
kind: Service
metadata:
  labels:
    app: webterm-service
  name: webterm-service
  # namespace: sharedservices
spec:
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 7681
      name: http
  selector:
    app: webterm
  type: LoadBalancer